## Data cleaning Vgchartz

In [20]:
import pandas as pd
import numpy as np
from datetime import datetime

In [2]:
df_vg = pd.read_csv("\\Users\\laura\\Desktop\\Progetto finale\\Videogames\\vgchartz_sales_uncleaned.csv")

In [3]:
df_vg

,videogame,platform,editor,developer,sales_na,sales_eu,sales_jp,sales_otras,sales_tot,release,genre
0,Tetris,Series,The Tetris Company,Alexey Pajitnov,NaN,NaN,NaN,NaN,NaN,01st Jan 88,Puzzle
1,Pokemon,Series,Nintendo,Game Freak,NaN,NaN,NaN,NaN,NaN,28th Sep 98,Role-Playing
2,Call of Duty,Series,Activision,Infinity Ward,NaN,NaN,NaN,NaN,NaN,29th Oct 03,Shooter
3,Grand Theft Auto,Series,Rockstar Games,Rockstar North,NaN,NaN,NaN,NaN,NaN,27th Mar 98,Action-Adventure
4,Super Mario,Series,Nintendo,Nintendo,NaN,NaN,NaN,NaN,NaN,20th Jul 83,Platform
...,...,...,...,...,...,...,...,...,...,...,...
64963,Zombieland: Double Tap - Road Trip,PC,GameMill Entertainment,High Voltage Software,NaN,NaN,NaN,NaN,NaN,15th Oct 19,Shooter
64964,Zombillie,NS,Forever Entertainment S.A.,Forever Entertainment S.A.,NaN,NaN,NaN,NaN,NaN,29th Mar 18,Puzzle
64965,Zone of the Enders: The 2nd Runner MARS,PC,Konami,Cygames,NaN,NaN,NaN,NaN,NaN,06th Sep 18,Simulation
64966,Zoo Tycoon: Ultimate Animal Collection,XOne,Microsoft Studios,Frontier Developments,NaN,NaN,NaN,NaN,NaN,31st Oct 17,Simulation
64967,Zoo Tycoon: Ultimate Animal Collection,PC,THQ Nordic,Frontier Developments,NaN,NaN,NaN,NaN,NaN,14th Sep 18,Simulation

In [4]:
df_vg.dropna(subset=['videogame'])

,videogame,platform,editor,developer,sales_na,sales_eu,sales_jp,sales_otras,sales_tot,release,genre
0,Tetris,Series,The Tetris Company,Alexey Pajitnov,NaN,NaN,NaN,NaN,NaN,01st Jan 88,Puzzle
1,Pokemon,Series,Nintendo,Game Freak,NaN,NaN,NaN,NaN,NaN,28th Sep 98,Role-Playing
2,Call of Duty,Series,Activision,Infinity Ward,NaN,NaN,NaN,NaN,NaN,29th Oct 03,Shooter
3,Grand Theft Auto,Series,Rockstar Games,Rockstar North,NaN,NaN,NaN,NaN,NaN,27th Mar 98,Action-Adventure
4,Super Mario,Series,Nintendo,Nintendo,NaN,NaN,NaN,NaN,NaN,20th Jul 83,Platform
...,...,...,...,...,...,...,...,...,...,...,...
64963,Zombieland: Double Tap - Road Trip,PC,GameMill Entertainment,High Voltage Software,NaN,NaN,NaN,NaN,NaN,15th Oct 19,Shooter
64964,Zombillie,NS,Forever Entertainment S.A.,Forever Entertainment S.A.,NaN,NaN,NaN,NaN,NaN,29th Mar 18,Puzzle
64965,Zone of the Enders: The 2nd Runner MARS,PC,Konami,Cygames,NaN,NaN,NaN,NaN,NaN,06th Sep 18,Simulation
64966,Zoo Tycoon: Ultimate Animal Collection,XOne,Microsoft Studios,Frontier Developments,NaN,NaN,NaN,NaN,NaN,31st Oct 17,Simulation
64967,Zoo Tycoon: Ultimate Animal Collection,PC,THQ Nordic,Frontier Developments,NaN,NaN,NaN,NaN,NaN,14th Sep 18,Simulation

In [5]:
df_vg['release'].isna().sum()

7587

In [6]:
no_date = df_vg[df_vg['release'].isna()]
no_date

,videogame,platform,editor,developer,sales_na,sales_eu,sales_jp,sales_otras,sales_tot,release,genre
1438,Infestation: Survivor Stories,PC,Unknown,Hammerpoint Interactive,NaN,NaN,NaN,NaN,NaN,NaN,Action-Adventure
1791,How to Survive 2,PC,Unknown,EKO Software,NaN,NaN,NaN,NaN,NaN,NaN,Action
1884,Stick Fight: The Game,PC,Unknown,Landfall West,NaN,NaN,NaN,NaN,NaN,NaN,Fighting
2099,Gran Turismo Concept 2001 Tokyo,PS2,Unknown,Polyphony Digital,NaN,1.1,0.42,0.33,1.84,NaN,Racing
2238,Human: Fall Flat,PC,Unknown,No Brakes Games,NaN,NaN,NaN,NaN,NaN,NaN,Platform
...,...,...,...,...,...,...,...,...,...,...,...
64937,Yurukill: The Calumniation Games,PS4,Unknown,G.rev Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,Visual Novel
64939,Zarvot,NS,Unknown,Snowhydra Games,NaN,NaN,NaN,NaN,NaN,NaN,Action
64950,ZJ the Ball Special,PS4,Unknown,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,Action
64953,Zombeer,WiiU,Unknown,Padaone Games,NaN,NaN,NaN,NaN,NaN,NaN,Action
64958,Zombie Brigade: No Brain No Gain,WiiU,Unknown,Cypron Studios,NaN,NaN,NaN,NaN,NaN,NaN,Action

In [7]:
def convert_date(date_str):
    if date_str.strip(): 
        date_str = date_str.replace("st", "").replace("nd", "").replace("rd", "").replace("th", "")
        date = datetime.strptime(date_str, "%d %b %y")
        formatted_date = date.strftime("%d/%m/%Y")
        return formatted_date
    else:
        return ""

In [9]:
df_vg['release'] = df_vg['release'].fillna("")

In [10]:
df_vg['release'] = df_vg['release'].apply(convert_date)

In [11]:
df_vg

,videogame,platform,editor,developer,sales_na,sales_eu,sales_jp,sales_otras,sales_tot,release,genre
0,Tetris,Series,The Tetris Company,Alexey Pajitnov,NaN,NaN,NaN,NaN,NaN,01/01/1988,Puzzle
1,Pokemon,Series,Nintendo,Game Freak,NaN,NaN,NaN,NaN,NaN,28/09/1998,Role-Playing
2,Call of Duty,Series,Activision,Infinity Ward,NaN,NaN,NaN,NaN,NaN,29/10/2003,Shooter
3,Grand Theft Auto,Series,Rockstar Games,Rockstar North,NaN,NaN,NaN,NaN,NaN,27/03/1998,Action-Adventure
4,Super Mario,Series,Nintendo,Nintendo,NaN,NaN,NaN,NaN,NaN,20/07/1983,Platform
...,...,...,...,...,...,...,...,...,...,...,...
64963,Zombieland: Double Tap - Road Trip,PC,GameMill Entertainment,High Voltage Software,NaN,NaN,NaN,NaN,NaN,15/10/2019,Shooter
64964,Zombillie,NS,Forever Entertainment S.A.,Forever Entertainment S.A.,NaN,NaN,NaN,NaN,NaN,29/03/2018,Puzzle
64965,Zone of the Enders: The 2nd Runner MARS,PC,Konami,Cygames,NaN,NaN,NaN,NaN,NaN,06/09/2018,Simulation
64966,Zoo Tycoon: Ultimate Animal Collection,XOne,Microsoft Studios,Frontier Developments,NaN,NaN,NaN,NaN,NaN,31/10/2017,Simulation
64967,Zoo Tycoon: Ultimate Animal Collection,PC,THQ Nordic,Frontier Developments,NaN,NaN,NaN,NaN,NaN,14/09/2018,Simulation

In [12]:
df_vg = df_vg.drop_duplicates()

In [13]:
df_vg

,videogame,platform,editor,developer,sales_na,sales_eu,sales_jp,sales_otras,sales_tot,release,genre
0,Tetris,Series,The Tetris Company,Alexey Pajitnov,NaN,NaN,NaN,NaN,NaN,01/01/1988,Puzzle
1,Pokemon,Series,Nintendo,Game Freak,NaN,NaN,NaN,NaN,NaN,28/09/1998,Role-Playing
2,Call of Duty,Series,Activision,Infinity Ward,NaN,NaN,NaN,NaN,NaN,29/10/2003,Shooter
3,Grand Theft Auto,Series,Rockstar Games,Rockstar North,NaN,NaN,NaN,NaN,NaN,27/03/1998,Action-Adventure
4,Super Mario,Series,Nintendo,Nintendo,NaN,NaN,NaN,NaN,NaN,20/07/1983,Platform
...,...,...,...,...,...,...,...,...,...,...,...
64963,Zombieland: Double Tap - Road Trip,PC,GameMill Entertainment,High Voltage Software,NaN,NaN,NaN,NaN,NaN,15/10/2019,Shooter
64964,Zombillie,NS,Forever Entertainment S.A.,Forever Entertainment S.A.,NaN,NaN,NaN,NaN,NaN,29/03/2018,Puzzle
64965,Zone of the Enders: The 2nd Runner MARS,PC,Konami,Cygames,NaN,NaN,NaN,NaN,NaN,06/09/2018,Simulation
64966,Zoo Tycoon: Ultimate Animal Collection,XOne,Microsoft Studios,Frontier Developments,NaN,NaN,NaN,NaN,NaN,31/10/2017,Simulation
64967,Zoo Tycoon: Ultimate Animal Collection,PC,THQ Nordic,Frontier Developments,NaN,NaN,NaN,NaN,NaN,14/09/2018,Simulation

In [14]:
def convert_to_millions_as_int(number):
    if pd.notnull(number): 
        return int(number * 1_000_000)
    else:
        return None

In [15]:
df_vg['sales_na'] = df_vg['sales_na'].apply(convert_to_millions_as_int)

C:\Users\laura\AppData\Local\Temp\ipykernel_11604\214698146.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_vg['sales_na'] = df_vg['sales_na'].apply(convert_to_millions_as_int)

In [16]:
df_vg['sales_eu'] = df_vg['sales_eu'].apply(convert_to_millions_as_int)

C:\Users\laura\AppData\Local\Temp\ipykernel_11604\366646128.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_vg['sales_eu'] = df_vg['sales_eu'].apply(convert_to_millions_as_int)

In [17]:
df_vg['sales_jp'] = df_vg['sales_jp'].apply(convert_to_millions_as_int)

C:\Users\laura\AppData\Local\Temp\ipykernel_11604\627076278.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_vg['sales_jp'] = df_vg['sales_jp'].apply(convert_to_millions_as_int)

In [18]:
df_vg['sales_otras'] = df_vg['sales_otras'].apply(convert_to_millions_as_int)

C:\Users\laura\AppData\Local\Temp\ipykernel_11604\4185432001.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_vg['sales_otras'] = df_vg['sales_otras'].apply(convert_to_millions_as_int)

In [23]:
df_vg['sales_tot'] = df_vg['sales_tot'].apply(convert_to_millions_as_int)

C:\Users\laura\AppData\Local\Temp\ipykernel_11604\65152700.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_vg.loc['sales_tot'] = df_vg['sales_tot'].apply(convert_to_millions_as_int)

In [22]:
df_vg.loc[df_vg['release'] == '', 'release'] = np.nan

In [24]:
df_vg

,videogame,platform,editor,developer,sales_na,sales_eu,sales_jp,sales_otras,sales_tot,release,genre
0,Tetris,Series,The Tetris Company,Alexey Pajitnov,NaN,NaN,NaN,NaN,NaN,01/01/1988,Puzzle
1,Pokemon,Series,Nintendo,Game Freak,NaN,NaN,NaN,NaN,NaN,28/09/1998,Role-Playing
2,Call of Duty,Series,Activision,Infinity Ward,NaN,NaN,NaN,NaN,NaN,29/10/2003,Shooter
3,Grand Theft Auto,Series,Rockstar Games,Rockstar North,NaN,NaN,NaN,NaN,NaN,27/03/1998,Action-Adventure
4,Super Mario,Series,Nintendo,Nintendo,NaN,NaN,NaN,NaN,NaN,20/07/1983,Platform
...,...,...,...,...,...,...,...,...,...,...,...
64964,Zombillie,NS,Forever Entertainment S.A.,Forever Entertainment S.A.,NaN,NaN,NaN,NaN,NaN,29/03/2018,Puzzle
64965,Zone of the Enders: The 2nd Runner MARS,PC,Konami,Cygames,NaN,NaN,NaN,NaN,NaN,06/09/2018,Simulation
64966,Zoo Tycoon: Ultimate Animal Collection,XOne,Microsoft Studios,Frontier Developments,NaN,NaN,NaN,NaN,NaN,31/10/2017,Simulation
64967,Zoo Tycoon: Ultimate Animal Collection,PC,THQ Nordic,Frontier Developments,NaN,NaN,NaN,NaN,NaN,14/09/2018,Simulation
sales_tot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df_vg.to_csv('vgchartz_sales.csv', index=False)